# EXERCISE INSTRUCTIONS
# This script should output a list of column names from a CSV file with any spaces replaced by underscores (the '_' character)
# This script was started by someone else, and you've been asked to fix any errors and provide this functionality

# Import pandas 
import pandas


data = pandas.read_csv("weather_data/weather_year.csv")

col_names = data.columns.values.tolist()
print col_names

# testing 
print "Testing right here!"
print len(data)
extra_string = data[" Events"] 
print extra_string


# STEP 1 - Define a function below called "replace_whitespace" that can replace characters in a string with others. The function should take two parameters, the first being the string that needs whitespace characters replacing, and the second being the character to insert instead of the whitespace.
def replace_whitespaces(input_Str, str1):
	input_Str = input_Str.replace(" ", str1)
	return input_Str	
# end of the function 	

# STEP 2 - output the new column names generated by running your replace_whitespace function
# BONUS - trim any leading (at the front of the string) or trailing (at the end) whitespace characters from each column name before you call your replace_whitespace function
print data.columns
Col_String = data.columns
New_Col = []

for n in range(len(Col_String)):
    Col_String[n].lstrip(' ')
    Col_String[n].rstrip(' ') 		
    New_Col.append(replace_whitespaces(Col_String[n], "_"))


print New_Col


# STEP 3 - Using the shell:
# (a) write ONLY the new non-whitespace column names to a new file called columnNames instead of the shell output (stdout)
# (b) similarly, sort the outputted column names into a new file called sortedColumnNames

# Push the following files to Aleksandra's github: this file containing the fixed code, file with the column names with spaces removed, and the file with the sorted names
# This will raise a pull request, so we can check your script

data.columns = New_Col
data.to_csv("weather_data/columnNames.csv")

data.columns = New_Col.sort()
data.to_csv("weather_data/sortedColumnNames.csv")


